# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-js-ipfs:
    docker:
      - image: circleci/node:10.15
      - image: joincolony/js-ipfs:latest
        command: daemon --enable-pubsub-experiment

    working_directory: ~/pinion

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Running Tests"
          environment:
            TEST_DAEMON_URL: /ip4/127.0.0.1/tcp/5002
            TEST_NODE_URL: /ip4/127.0.0.1/tcp/4002/ipfs
            CI_API_PORT: 5002
          command: |
            mkdir -p reports/ava
            yarn test:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
  test-go-ipfs:
    docker:
      - image: circleci/node:10.15
      - image: ipfs/go-ipfs:latest
        command: daemon --enable-pubsub-experiment

    working_directory: ~/pinion

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Running Tests"
          environment:
            CI_API_PORT: 5001
          command: |
            mkdir -p reports/ava
            yarn test:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

workflows:
  version: 2
  commit:
    jobs:
      - test-js-ipfs
      - test-go-ipfs

